### PR TITLE
added idowapro

### PR DESCRIPTION
**Pull request by TheOnlySpeedy**

### CODE REVIEW

**Review by kermie — CHANGES_REQUESTED** [review]
Acronyms shall have at least two but not more than four characters. How did you name your modules before introduction of namespaces: ipro or idowapro?

**Comment by TheOnlySpeedy** [comment]
oh i thought it would be okay to use idowapro because there also other acronyms that are longer than 4 characters.
For example "spark5" and "ifabrik"
Before namespaces we named them idowapro, but i think we can name the new modules ipro, but i have to check this first

**Comment by kermie** [comment]
Look, I don't want to be too anal about that. Of course, it depends on the extension acronym (first row) you used so far in your modules. If you just start writing modules and have not done that before, please consider to use the shorter one. If your modules are already widespread, and you used the long version - as long as it works... My information is that a too long acronym might have broken the module functionality but am not clear about the exact number of characters (and nobody else is :D).
Namespace (second row) is something totally different: http://php.net/manual/en/language.namespaces.php

**Comment by TheOnlySpeedy** [comment]
changed the acronym from "idowapro" to "ipro"

**Pull request merged**
